# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='email',
        ),
        migrations.AddField(
            model_name='email',
            name='emails',
            field=models.CharField(default='test@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
